# frozen_string_literal: true
# ═══════════════════════════════════════════════════════════════
# MachiningInterpreter — Declarative ferragens_auto → CNC workers
#
# Reads the `ferragens_auto` array from a JSON module definition
# plus the ShopConfig for this module, and produces per-piece
# CNC operation hashes identical to those generated by RulesEngine.
#
# The key difference from RulesEngine:
#   • RulesEngine uses AABB geometry detection (fragile, misses role aliases)
#   • MachiningInterpreter uses DECLARATIVE rules from the JSON ("lateral × base")
#
# This means JSON modules always get the right machining regardless of
# how pieces are spatially arranged in SketchUp.
#
# ── Data flow ─────────────────────────────────────────────────
#   JSON ferragens_auto
#       + ShopConfig (merged per module)
#       + Module params ({ 'largura' => 600, ... })
#       + pieces_data (Array of piece info hashes from DialogController)
#   ──────────────────────────────────────────────────────────────
#   { piece_persistent_id => [{ category:, position_x:, ... }, ...] }
#
# ── Supported ferragens_auto rule types ───────────────────────
#   minifix    juncao: "lateral_esq × base"
#   cavilha    juncao: "lateral_esq × base"
#   confirmat  juncao: "lateral_esq × base"
#   dobradica  peca:   "lateral_esq"
#   puxador    peca:   "porta" / "frente_gaveta"
#   system32   pecas:  ["lateral_esq", "lateral_dir"]
#   rebaixo_fundo pecas: ["lateral_esq", "lateral_dir", "base"]
#   corredica  peca:   "lateral_esq"
#   rasgo_led  peca:   "prateleira"
#   pistao     peca:   "topo"
#   cavilha_ripa painel: "panel", ripa: "slat"
# ═══════════════════════════════════════════════════════════════

require_relative '../core/logger'

module Ornato
  module Machining
    class MachiningInterpreter

      # Mapping from ShopConfig string keys → hardware rule symbol keys
      SHOP_KEY_MAP = {
        'dobradica'    => :hinge,
        'minifix'      => :minifix,
        'confirmat'    => :confirmat,
        'cavilha'      => :dowel,
        'puxador'      => :handle,
        'corredica'    => :drawer_slide,
        'system32'     => :system32,
        'rasgo_fundo'  => :back_panel,
        'pistao'       => :gas_piston,
      }.freeze

      # ─── Public API ──────────────────────────────────────────

      # @param shop_config [Hash]  merged ShopConfig for this module
      #   (string keys: 'dobradica', 'minifix', 'juncao', etc.)
      # @param params [Hash]  module params, any key types
      #   ({ 'largura' => 600, 'tipo_porta' => '2_abrir', ... })
      def initialize(shop_config, params = {})
        @cfg    = shop_config
        @params = stringify_keys(params)
      end

      # Interpret ferragens_auto rules for a set of pieces.
      #
      # @param ferragens_auto [Array<Hash>]  from JSON module definition
      # @param pieces_data [Array<Hash>]  each:
      #   { id: pid, role: :lateral, dims: { w:, h:, t: }, name:, origin: }
      # @return [Hash] pid => Array<Hash> of CNC operation hashes
      def interpret(ferragens_auto, pieces_data)
        return {} if ferragens_auto.nil? || ferragens_auto.empty?
        return {} if pieces_data.nil?   || pieces_data.empty?

        pieces  = build_virtual_pieces(pieces_data)
        active  = evaluate_active_rules(ferragens_auto)

        joints, hardware = build_joints_and_hardware(active, pieces)

        # Ensure handle suppression for pieces not in any puxador rule
        suppress_default_handles(hardware, pieces, active)

        rules_config = build_rules_config

        result = {}

        pieces.each do |piece|
          workers    = {}
          op_counter = 0

          direct_ops_for_piece(piece, active, pieces).each do |op|
            workers["op_#{op_counter}"] = op
            op_counter += 1
          end

          rule_classes.each do |klass|
            rule = klass.new(rules_config)
            next unless safe_applies?(rule, piece, joints, hardware)

            ops = safe_generate(rule, piece, joints, hardware)
            ops.each do |op|
              workers["op_#{op_counter}"] = op
              op_counter += 1
            end
          end

          result[piece.persistent_id] = workers unless workers.empty?
        end

        result
      end

      # ─── Private ─────────────────────────────────────────────
      private

      # ── 1. Build virtual Piece objects from DialogController data ──

      def build_virtual_pieces(pieces_data)
        pieces_data.map do |pd|
          dims = pd[:dims] || pd['dims'] || {}
          role_raw = pd[:role] || pd['role'] || :generic

          Hardware::Piece.new(
            entity:        nil,
            width:         (dims[:w] || dims['w'] || 0).to_f,
            height:        (dims[:h] || dims['h'] || 0).to_f,
            thickness:     (dims[:t] || dims['t'] || 18).to_f,
            role:          normalize_role(role_raw),
            persistent_id: pd[:id] || pd['id'] || pd[:persistent_id] || pd['persistent_id'],
            origin:        pd[:origin] || pd['origin'] || [0.0, 0.0, 0.0]
          )
        end
      end

      # ── 2. Filter active rules by evaluating conditions ──────

      def evaluate_active_rules(ferragens_auto)
        ferragens_auto.select do |r|
          # Regras com `componente_3d` sao tratadas pelo
          # FerragemDrillingCollector (extracao de furacoes da .skp WPS).
          # Pular aqui evita duplicar operacoes durante a migracao legacy→3D.
          next false if r.is_a?(Hash) && r['componente_3d']
          condition_met?(r['condicao'])
        end
      end

      # ── 3. Build virtual Joint objects + hardware dict ────────
      #
      # Each ferragens_auto rule maps to one or more virtual joints
      # that the existing rule classes understand.

      def build_joints_and_hardware(active_rules, pieces)
        joints   = []
        hardware = {}

        # Track which rule types are present (to know what to suppress)
        @active_rule_types = active_rules.map { |r| r['regra'] }.compact.uniq

        active_rules.each do |regra|
          rule_type = regra['regra']
          next if rule_type.nil?

          case rule_type

          # ── Structural junction rules ──────────────────────────

          when 'minifix', 'cavilha', 'confirmat'
            add_junction_joints(joints, pieces, regra)

          # ── Hinge (dobradiça) rule ─────────────────────────────
          # Creates overlay joints between lateral → door(s)

          when 'dobradica'
            lat_role  = normalize_role(regra['peca'] || 'lateral_esq')
            laterais  = find_by_role(pieces, lat_role)
            portas    = find_by_role(pieces, :door)

            laterais.each do |lat|
              portas.each do |door|
                joints << make_joint(lat, door, :overlay, :front, :front,
                                     contact_along_height(door))
              end
            end

          # ── Gas piston ─────────────────────────────────────────

          when 'pistao'
            peca_role = normalize_role(regra['peca'] || 'topo')
            tops      = find_by_role(pieces, peca_role)
            portas    = find_by_role(pieces, :door)

            tops.each do |top|
              portas.each do |door|
                joints << make_joint(top, door, :overlay, :front, :top,
                                     contact_along_height(door))
              end
            end

          # ── Drawer slides ──────────────────────────────────────

          when 'corredica'
            lat_role = normalize_role(regra['peca'] || 'lateral_esq')
            laterais = find_by_role(pieces, lat_role)
            drawers  = find_by_role(pieces, :drawer_front) +
                       find_by_role(pieces, :drawer_side)

            laterais.each do |lat|
              drawers.each do |drw|
                joints << make_joint(lat, drw, :butt, :front, :left,
                                     contact_along_height(drw))
              end
            end

          # ── Back panel rebate (dado) ───────────────────────────

          when 'rebaixo_fundo'
            target_roles = collect_roles(regra)
            back_panels  = find_by_role(pieces, :back_panel)

            target_roles.each do |role|
              find_by_role(pieces, role).each do |target|
                back_panels.each do |bp|
                  joints << make_joint(target, bp, :dado, :back, :back,
                                       [target.width, target.height].min)
                end
              end
            end

            # If no explicit back_panel piece exists, still mark the dado
            # so BackPanelRule fires — use a phantom back panel piece.
            if back_panels.empty? && !target_roles.empty?
              phantom = make_phantom_back_panel(pieces)
              target_roles.each do |role|
                find_by_role(pieces, role).each do |target|
                  joints << make_joint(target, phantom, :dado, :back, :back,
                                       [target.width, target.height].min)
                end
              end
            end

          # ── System 32 shelving holes ───────────────────────────

          when 'system32'
            collect_roles(regra).each do |role|
              find_by_role(pieces, role).each do |piece|
                hardware[piece.persistent_id] ||= {}
                hardware[piece.persistent_id]['system32'] = true
              end
            end

          # ── Handle / puxador ───────────────────────────────────

          when 'puxador'
            target_role = normalize_role(regra['peca'] || 'porta')
            spacing     = (@params['puxador_espacamento'] ||
                           @cfg.dig('puxador', 'espacamento') ||
                           160).to_f

            find_by_role(pieces, target_role).each do |piece|
              hardware[piece.persistent_id] ||= {}
              hardware[piece.persistent_id]['handle']         = true
              hardware[piece.persistent_id]['handle_spacing'] = spacing
            end

          # ── LED channel groove ─────────────────────────────────

          when 'rasgo_led'
            # LEDChannelRule uses piece role detection (shelf? etc.)
            # No joint needed — just ensure the pieces exist

          end
        end

        [joints, hardware]
      end

      # ── 4. Suppress handles for pieces not in any puxador rule ──

      def suppress_default_handles(hardware, pieces, active_rules)
        return if @active_rule_types.include?('puxador')

        # No puxador rule at all — suppress HandleRule for all doors/drawer fronts
        pieces.each do |piece|
          next unless piece.door? || piece.drawer_front? || piece.drawer?
          hardware[piece.persistent_id] ||= {}
          hardware[piece.persistent_id]['handle'] = false unless
            hardware[piece.persistent_id]['handle']
        end
      end

      # ── 5. Build rules config from ShopConfig ─────────────────
      #
      # Hardware rules expect symbol keys (:minifix, :hinge, etc.)
      # ShopConfig uses string keys ('minifix', 'dobradica', etc.)

      def build_rules_config
        cfg = {}

        # Map ShopConfig string keys → rule symbol keys
        SHOP_KEY_MAP.each do |shop_key, rule_key|
          val = @cfg[shop_key]
          next unless val.is_a?(Hash)
          cfg[rule_key] = symbolize_keys(val)
        end

        # Default joint type for MinifixRule / ConfirmatRule
        juncao = @params['tipo_juncao'] || @cfg['juncao'] || 'minifix'
        cfg[:default_joint_type] = juncao

        # DrawerSlide: map hole patterns from ShopConfig catalog
        slide_modelo = @cfg.dig('corredica', 'modelo') || 'tandem_push'
        if defined?(Hardware::ShopConfig)
          # Pull hole patterns from catalog
          catalog_slide = Hardware::ShopConfig::HARDWARE_CATALOG['corredica']
                          &.find { |c| c['id'] == slide_modelo }
          if catalog_slide&.[]('holes')
            cfg[:drawer_slide] ||= {}
            patterns = {}
            catalog_slide['holes'].each { |k, v| patterns[k.to_i] = v }
            cfg[:drawer_slide][:patterns] = patterns
          end
        end

        cfg
      end

      # ══════════════════════════════════════════════════════════
      # Helper Methods
      # ══════════════════════════════════════════════════════════

      def normalize_role(raw)
        if defined?(Core::RoleNormalizer)
          Core::RoleNormalizer.normalize(raw)
        else
          raw.to_sym
        end
      end

      def find_by_role(pieces, role)
        pieces.select { |p| p.role == role.to_sym }
      end

      def collect_roles(regra)
        if regra['pecas'].is_a?(Array)
          regra['pecas'].map { |r| normalize_role(r) }
        elsif regra['peca']
          [normalize_role(regra['peca'])]
        else
          []
        end
      end

      # ── Direct declarative machining rules ───────────────────
      # Algumas operações não são junção de caixaria tradicional.
      # Ex.: painel ripado, onde cada ripa gabarita furos no painel base.
      def direct_ops_for_piece(piece, active_rules, pieces)
        ops = []

        active_rules.each do |regra|
          case regra['regra'] || regra['tipo']
          when 'cavilha_ripa', 'slat_dowel'
            ops.concat(slat_dowel_ops(piece, regra, pieces))
          end
        end

        ops
      end

      def slat_dowel_ops(piece, regra, pieces)
        panel_role = normalize_role(regra['painel'] || regra['panel'] || 'panel')
        slat_role  = normalize_role(regra['ripa']   || regra['slat']  || 'slat')

        panel = find_by_role(pieces, panel_role).first
        slats = find_by_role(pieces, slat_role)
        return [] unless panel && slats.any?
        return [] unless piece.role == panel_role || piece.role == slat_role

        diameter = numeric_rule_value(regra, 'diametro', 8.0)
        tool = regra['tool_code'] || "broca_#{diameter.to_i}mm"
        positions_y = vertical_dowel_positions(panel.height, regra)

        if piece.role == panel_role
          panel_slat_dowel_ops(piece, panel, slats, positions_y, regra, diameter, tool)
        else
          slat_piece_dowel_ops(piece, positions_y, regra, diameter, tool)
        end
      end

      def panel_slat_dowel_ops(_piece, panel, slats, positions_y, regra, diameter, tool)
        depth = numeric_rule_value(regra, 'profundidade_painel', 12.0)

        slats.each_with_index.flat_map do |slat, slat_idx|
          center_x = (slat.origin[0].to_f - panel.origin[0].to_f) + (slat.width / 2.0)

          positions_y.each_with_index.map do |y_pos, pos_idx|
            {
              'category'    => 'hole',
              'position_x'  => center_x.round(2),
              'position_y'  => y_pos.round(2),
              'diameter'    => diameter,
              'depth'       => depth,
              'side'        => 'a',
              'tool_code'   => tool,
              'description' => "Cavilha gabarito painel/ripa #{slat_idx + 1} - furo #{pos_idx + 1}/#{positions_y.size}",
            }
          end
        end
      end

      def slat_piece_dowel_ops(piece, positions_y, regra, diameter, tool)
        depth = numeric_rule_value(regra, 'profundidade_ripa', 15.0)
        center_x = piece.width / 2.0

        positions_y.each_with_index.map do |y_pos, idx|
          {
            'category'    => 'hole',
            'position_x'  => center_x.round(2),
            'position_y'  => y_pos.round(2),
            'diameter'    => diameter,
            'depth'       => depth,
            'side'        => 'b',
            'tool_code'   => tool,
            'description' => "Cavilha ripa/painel - furo #{idx + 1}/#{positions_y.size}",
          }
        end
      end

      def vertical_dowel_positions(height, regra)
        height = height.to_f
        margin_top = numeric_rule_value(regra, 'margem_topo', 120.0)
        margin_base = numeric_rule_value(regra, 'margem_base', 120.0)
        spacing = numeric_rule_value(regra, 'espacamento_vertical', 450.0)

        usable = height - margin_top - margin_base
        return [(height / 2.0).round(2)] if usable <= 0 || spacing <= 0

        count = (usable / spacing).ceil + 1
        count = [count, 2].max
        actual_spacing = usable / (count - 1).to_f

        (0...count).map { |idx| (margin_base + (idx * actual_spacing)).round(2) }
      end

      def numeric_rule_value(regra, key, default)
        raw = regra[key] || regra[key.to_sym]
        raw = regra[key.tr('_', '-')] if raw.nil? && key.include?('_')
        return default.to_f if raw.nil?
        return raw.to_f if raw.is_a?(Numeric)

        expr = raw.to_s.dup
        @params.each do |param_key, value|
          numeric = value.is_a?(Numeric) ? value.to_s : value.to_f.to_s
          expr = expr.gsub("{#{param_key}}", numeric)
        end

        clean = expr.strip.gsub(/[^0-9\+\-\*\/\(\)\.\s]/, '')
        return default.to_f if clean.empty?

        eval(clean).to_f
      rescue
        raw.to_f > 0 ? raw.to_f : default.to_f
      end

      def add_junction_joints(joints, pieces, regra)
        juncao = regra['juncao']
        return unless juncao

        # Parse "lateral_esq × base" — supports × (U+00D7), x, ×
        parts = juncao.split(/\s*[×x×]\s*/)
        return unless parts.length == 2

        role_a = normalize_role(parts[0].strip)
        role_b = normalize_role(parts[1].strip)

        pieces_a = find_by_role(pieces, role_a)
        pieces_b = find_by_role(pieces, role_b)

        pieces_a.each do |pa|
          pieces_b.each do |pb|
            joints << make_joint(
              pa, pb,
              :butt,
              junction_face(role_a, :a),
              junction_face(role_b, :b),
              contact_for_junction(pa, pb, role_a, role_b)
            )
          end
        end
      end

      def make_joint(piece_a, piece_b, type, face_a, face_b, contact_length)
        Hardware::Joint.new(
          piece_a:        piece_a,
          piece_b:        piece_b,
          type:           type,
          face_a:         face_a,
          face_b:         face_b,
          contact_length: contact_length.to_f
        )
      end

      # Create a phantom back_panel piece so BackPanelRule can detect thickness
      def make_phantom_back_panel(pieces)
        # Estimate back panel width/height from lateral dimensions
        lateral = find_by_role(pieces, :lateral).first
        base    = find_by_role(pieces, :base).first

        bp_width  = lateral ? lateral.height : 400.0
        bp_height = lateral ? lateral.width  : 700.0

        Hardware::Piece.new(
          entity:        nil,
          width:         bp_width,
          height:        bp_height,
          thickness:     3.0,  # standard 3mm back panel
          role:          :back_panel,
          persistent_id: '__phantom_back_panel__',
          origin:        [0.0, 0.0, 0.0]
        )
      end

      # Contact length for a butt junction between two pieces
      def contact_for_junction(pa, pb, role_a, role_b)
        case [role_a, role_b]
        when [:lateral, :base], [:lateral, :top], [:lateral, :shelf],
             [:lateral, :divider], [:base, :lateral], [:top, :lateral]
          # Contact = cabinet depth = smaller dimension of the horizontal piece
          [pa.height, pb.height].min
        when [:base, :base], [:top, :top]
          [pa.width, pb.width].max
        else
          # Fallback: smallest shared dimension
          [pa.width, pa.height, pb.width, pb.height].sort[1]
        end
      end

      def contact_along_height(piece)
        # For door: height = the door's tallest dimension (cabinet height direction)
        piece.width
      end

      # Determine which face of piece is the contact face for a junction role
      def junction_face(role, side)
        if side == :a
          # Role A = through piece (e.g., lateral)
          case role
          when :lateral   then :bottom
          when :base      then :right
          when :top       then :right
          when :divider   then :bottom
          else :bottom
          end
        else
          # Role B = end piece
          case role
          when :base      then :top
          when :top       then :bottom
          when :lateral   then :left
          when :divider   then :top
          else :top
          end
        end
      end

      # ── Condition evaluator (same logic as JsonModuleBuilder) ──

      def condition_met?(condition)
        return true if condition.nil? || condition.to_s.strip.empty?
        return true  if condition.to_s.strip == 'true'
        return false if condition.to_s.strip == 'false'

        expr = condition.to_s.dup

        @params.each do |key, value|
          replacement = case value
                        when TrueClass, FalseClass then value.to_s
                        when Numeric               then value.to_s
                        else "'#{value}'"
                        end
          expr = expr.gsub("{#{key}}", replacement)
        end

        # Handle leftover unresolved {params} as false-y
        expr = expr.gsub(/\{[^}]+\}/, 'nil')

        result = eval(expr) # safe: only module params, no user input
        result ? true : false
      rescue => e
        Ornato::Logger.warn("MachiningInterpreter: condition error", context: { condition: condition, error: e.message })
        true # include by default on error
      end

      # ── Safe wrappers for rule calls ──────────────────────────

      def safe_applies?(rule, piece, joints, hardware)
        rule.applies?(piece, joints, hardware)
      rescue => e
        Ornato::Logger.error("MachiningInterpreter#applies? error", context: { rule: rule.class.name, error: e.message })
        false
      end

      def safe_generate(rule, piece, joints, hardware)
        rule.generate(piece, joints, hardware)
      rescue => e
        Ornato::Logger.error("MachiningInterpreter#generate error", context: { rule: rule.class.name, error: e.message })
        []
      end

      # ── Rule class list (lazy to survive any load-order) ─────
      # Uses fully-qualified names; returns only defined classes.
      def rule_classes
        @rule_classes ||= [
          'Ornato::Hardware::HingeRule',
          'Ornato::Hardware::GasPistonRule',
          'Ornato::Hardware::SlidingDoorRule',
          'Ornato::Hardware::System32Rule',
          'Ornato::Hardware::MinifixRule',
          'Ornato::Hardware::ConfirmatRule',
          'Ornato::Hardware::DowelRule',
          'Ornato::Hardware::HandleRule',
          'Ornato::Hardware::DrawerSlideRule',
          'Ornato::Hardware::BackPanelRule',
          'Ornato::Hardware::ShelfRule',
          'Ornato::Hardware::LEDChannelRule',
          'Ornato::Hardware::PassThroughRule',
          'Ornato::Hardware::MiterRule',
        ].map do |class_name|
          Object.const_get(class_name)
        rescue NameError
          nil
        end.compact
      end

      # ── Hash key helpers ──────────────────────────────────────

      def stringify_keys(hash)
        result = {}
        hash.each { |k, v| result[k.to_s] = v }
        result
      end

      def symbolize_keys(hash)
        result = {}
        hash.each { |k, v| result[k.to_sym] = v }
        result
      end

    end
  end
end
